[build]
  command = "npm run build"
  publish = "_site"
  functions = "src/functions"

[dev]
  command = "npm run start"


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
